name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.85.0

jobs:
  build-test:
    name: "Build and Test 🔬"
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: sudo apt-get install libxcb1-dev libdbus-1-dev
      - uses: actions/checkout@v4
      - run: rustup toolchain install $RUST_VERSION --profile minimal
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo nextest run --no-fail-fast --retries 2
      - name: Output e2e test logs (on failure)
        if: failure()
        run: cat crates/tests/tattoy.log

  lints:
    name: "Lints 💅"
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: sudo apt-get install libdbus-1-dev
      - uses: actions/checkout@v4
      - run: rustup toolchain install $RUST_VERSION --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: cargo clippy -- --deny warnings
      - name: Formatting
        run: cargo fmt --check
